import type { Category, Product, Brand } from "./types";

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Textiles",
    slug: "textiles",
    description: "Playeras, gorras, chamarras y mas prendas personalizables.",
    image: "/images/categories/textiles.jpg",
    icon: "Shirt",
    accentColor: "primary",
    productCount: 45,
  },
  {
    id: "cat-2",
    name: "Escritura",
    slug: "escritura",
    description: "Plumas, lapices, boligrafos ejecutivos y sets de escritura.",
    image: "/images/categories/escritura.jpg",
    icon: "PenTool",
    accentColor: "coral",
    productCount: 32,
  },
  {
    id: "cat-3",
    name: "Tecnologia",
    slug: "tecnologia",
    description: "USB, power banks, audifonos y gadgets tecnologicos.",
    image: "/images/categories/tecnologia.jpg",
    icon: "Smartphone",
    accentColor: "purple",
    productCount: 28,
  },
  {
    id: "cat-4",
    name: "Drinkware",
    slug: "drinkware",
    description: "Termos, tazas, vasos y botellas personalizadas.",
    image: "/images/categories/drinkware.jpg",
    icon: "Coffee",
    accentColor: "mint",
    productCount: 36,
  },
  {
    id: "cat-5",
    name: "Bolsas",
    slug: "bolsas",
    description: "Bolsas ecologicas, mochilas, maletines y portafolios.",
    image: "/images/categories/bolsas.jpg",
    icon: "ShoppingBag",
    accentColor: "electric",
    productCount: 24,
  },
  {
    id: "cat-6",
    name: "Oficina",
    slug: "oficina",
    description: "Libretas, organizadores, portanotas y accesorios de escritorio.",
    image: "/images/categories/oficina.jpg",
    icon: "Briefcase",
    accentColor: "primary",
    productCount: 20,
  },
];

export const products: Product[] = [
  // Textiles
  {
    id: "prod-1",
    name: "Playera Dry-Fit Premium",
    slug: "playera-dry-fit-premium",
    description: "Playera deportiva Dry-Fit con tecnologia de absorcion de humedad. Ideal para eventos deportivos, carreras y actividades al aire libre. Tejido ligero y transpirable que mantiene la frescura todo el dia.",
    shortDescription: "Playera deportiva con tecnologia Dry-Fit.",
    categoryId: "cat-1",
    brandId: "brand-1",
    images: ["/images/products/playera-dryfit-1.jpg", "/images/products/playera-dryfit-2.jpg"],
    price: 89,
    minOrder: 50,
    specs: [
      { label: "Material", value: "100% Poliester Dry-Fit" },
      { label: "Peso", value: "135 g/m2" },
      { label: "Tallas", value: "S, M, L, XL, 2XL" },
      { label: "Area de impresion", value: "30 x 40 cm" },
    ],
    variants: [
      { sku: "PDF-BL-M", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "PDF-NE-M", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "PDF-AZ-M", color: "Azul Rey", colorHex: "#1d4ed8", stock: "disponible" },
      { sku: "PDF-RO-M", color: "Rojo", colorHex: "#dc2626", stock: "bajo" },
      { sku: "PDF-GR-M", color: "Gris", colorHex: "#6b7280", stock: "disponible" },
    ],
    techniques: ["serigrafia", "sublimacion", "transfer"],
    isFeatured: true,
  },
  {
    id: "prod-2",
    name: "Gorra Estructurada 6 Paneles",
    slug: "gorra-estructurada-6-paneles",
    description: "Gorra de 6 paneles con estructura frontal rigida y cierre de velcro ajustable. Acabado premium con visera curva. Perfecta para uniformes y campanas de marca.",
    shortDescription: "Gorra clasica estructurada con 6 paneles.",
    categoryId: "cat-1",
    images: ["/images/products/gorra-1.jpg"],
    price: 65,
    minOrder: 100,
    specs: [
      { label: "Material", value: "Algodón con poliester" },
      { label: "Paneles", value: "6" },
      { label: "Cierre", value: "Velcro ajustable" },
      { label: "Area de bordado", value: "10 x 6 cm" },
    ],
    variants: [
      { sku: "GE6-BL", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "GE6-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "GE6-AZ", color: "Azul Marino", colorHex: "#1e3a5f", stock: "disponible" },
      { sku: "GE6-RO", color: "Rojo", colorHex: "#dc2626", stock: "agotado" },
    ],
    techniques: ["bordado", "serigrafia"],
    isFeatured: true,
  },
  {
    id: "prod-3",
    name: "Chamarra Softshell Ejecutiva",
    slug: "chamarra-softshell-ejecutiva",
    description: "Chamarra softshell con forro interior polar. Resistente al viento y lluvia ligera. Ideal para uniformes corporativos y regalos ejecutivos.",
    shortDescription: "Chamarra softshell con forro polar.",
    categoryId: "cat-1",
    brandId: "brand-2",
    images: ["/images/products/chamarra-1.jpg"],
    price: 350,
    minOrder: 25,
    specs: [
      { label: "Material", value: "Softshell 3 capas" },
      { label: "Forro", value: "Micro polar" },
      { label: "Tallas", value: "S, M, L, XL, 2XL" },
      { label: "Area de bordado", value: "12 x 8 cm (pecho)" },
    ],
    variants: [
      { sku: "CSE-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "CSE-AM", color: "Azul Marino", colorHex: "#1e3a5f", stock: "disponible" },
      { sku: "CSE-GR", color: "Gris Oxford", colorHex: "#4b5563", stock: "bajo" },
    ],
    techniques: ["bordado"],
    isFeatured: false,
  },
  // Escritura
  {
    id: "prod-4",
    name: "Boligrafo Metalico Executive",
    slug: "boligrafo-metalico-executive",
    description: "Boligrafo de cuerpo metalico con acabado mate y clip cromado. Tinta negra de alta calidad. Presentacion individual en estuche de carton.",
    shortDescription: "Boligrafo metalico con acabado mate.",
    categoryId: "cat-2",
    brandId: "brand-3",
    images: ["/images/products/boligrafo-1.jpg"],
    price: 35,
    minOrder: 100,
    specs: [
      { label: "Material", value: "Aluminio anodizado" },
      { label: "Largo", value: "14 cm" },
      { label: "Tinta", value: "Negra, punta media" },
      { label: "Area de grabado", value: "5 x 0.8 cm" },
    ],
    variants: [
      { sku: "BME-PL", color: "Plata", colorHex: "#C0C0C0", stock: "disponible" },
      { sku: "BME-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "BME-AZ", color: "Azul", colorHex: "#2563eb", stock: "disponible" },
      { sku: "BME-DO", color: "Dorado", colorHex: "#d4a437", stock: "bajo" },
    ],
    techniques: ["grabado-laser", "tampografia"],
    isFeatured: true,
  },
  {
    id: "prod-5",
    name: "Set Pluma y Lapicero Premium",
    slug: "set-pluma-lapicero-premium",
    description: "Set ejecutivo de pluma y lapicero mecanico en estuche de madera lacada. Acabado cromado y cuerpo en resina negra. Regalo corporativo de alta gama.",
    shortDescription: "Set ejecutivo pluma y lapicero en estuche.",
    categoryId: "cat-2",
    images: ["/images/products/set-pluma-1.jpg"],
    price: 180,
    minOrder: 25,
    specs: [
      { label: "Material", value: "Resina con acabado cromado" },
      { label: "Estuche", value: "Madera lacada" },
      { label: "Incluye", value: "Pluma + Lapicero mecanico" },
      { label: "Area de grabado", value: "4 x 0.6 cm por pieza" },
    ],
    variants: [
      { sku: "SPLP-NE", color: "Negro / Cromado", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "SPLP-AM", color: "Azul Marino / Cromado", colorHex: "#1e3a5f", stock: "disponible" },
    ],
    techniques: ["grabado-laser"],
    isFeatured: false,
  },
  // Tecnologia
  {
    id: "prod-6",
    name: "Power Bank 10000 mAh",
    slug: "power-bank-10000-mah",
    description: "Bateria portatil de 10,000 mAh con doble puerto USB y entrada Type-C. Indicador LED de carga. Cuerpo delgado y ligero con acabado premium.",
    shortDescription: "Bateria portatil 10,000 mAh doble USB.",
    categoryId: "cat-3",
    brandId: "brand-4",
    images: ["/images/products/powerbank-1.jpg"],
    price: 220,
    minOrder: 50,
    specs: [
      { label: "Capacidad", value: "10,000 mAh" },
      { label: "Salida", value: "2x USB-A (5V/2.1A)" },
      { label: "Entrada", value: "Micro-USB / Type-C" },
      { label: "Area de impresion", value: "8 x 5 cm" },
    ],
    variants: [
      { sku: "PB10-BL", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "PB10-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "PB10-PL", color: "Plata", colorHex: "#C0C0C0", stock: "bajo" },
    ],
    techniques: ["serigrafia", "grabado-laser"],
    isFeatured: true,
  },
  {
    id: "prod-7",
    name: "USB Bambu 16GB",
    slug: "usb-bambu-16gb",
    description: "Memoria USB ecologica con cuerpo de bambu natural y tapa magnetica. 16GB de almacenamiento. Opcion sustentable y elegante para tu marca.",
    shortDescription: "Memoria USB ecologica de bambu 16GB.",
    categoryId: "cat-3",
    images: ["/images/products/usb-bambu-1.jpg"],
    price: 95,
    minOrder: 100,
    specs: [
      { label: "Capacidad", value: "16 GB" },
      { label: "Material", value: "Bambu natural" },
      { label: "Interfaz", value: "USB 2.0" },
      { label: "Area de grabado", value: "3 x 1.5 cm" },
    ],
    variants: [
      { sku: "UBB-16", color: "Bambu Natural", colorHex: "#d4a76a", stock: "disponible" },
    ],
    techniques: ["grabado-laser"],
    isFeatured: false,
  },
  {
    id: "prod-8",
    name: "Audifonos Bluetooth Personalizados",
    slug: "audifonos-bluetooth-personalizados",
    description: "Audifonos inalambricos Bluetooth 5.0 con estuche de carga personalizable. 4 horas de reproduccion. Diseno compacto y moderno.",
    shortDescription: "Audifonos Bluetooth 5.0 con estuche.",
    categoryId: "cat-3",
    images: ["/images/products/audifonos-1.jpg"],
    price: 185,
    minOrder: 50,
    specs: [
      { label: "Conectividad", value: "Bluetooth 5.0" },
      { label: "Bateria", value: "4h reproduccion" },
      { label: "Estuche", value: "Con carga, 12h total" },
      { label: "Area de impresion", value: "3 x 2 cm (estuche)" },
    ],
    variants: [
      { sku: "ABT-BL", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "ABT-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
    ],
    techniques: ["tampografia", "serigrafia"],
    isFeatured: true,
  },
  // Drinkware
  {
    id: "prod-9",
    name: "Termo Acero Inoxidable 500ml",
    slug: "termo-acero-inoxidable-500ml",
    description: "Termo de doble pared de acero inoxidable con capacidad de 500ml. Mantiene bebidas calientes 12h y frias 24h. Tapa hermetica anti-derrames.",
    shortDescription: "Termo doble pared acero inox 500ml.",
    categoryId: "cat-4",
    brandId: "brand-2",
    images: ["/images/products/termo-1.jpg"],
    price: 150,
    minOrder: 50,
    specs: [
      { label: "Capacidad", value: "500 ml" },
      { label: "Material", value: "Acero inoxidable 18/8" },
      { label: "Aislamiento", value: "Doble pared al vacio" },
      { label: "Area de grabado", value: "6 x 4 cm" },
    ],
    variants: [
      { sku: "TAI-BL", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "TAI-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "TAI-AZ", color: "Azul", colorHex: "#2563eb", stock: "disponible" },
      { sku: "TAI-RO", color: "Rojo", colorHex: "#dc2626", stock: "disponible" },
      { sku: "TAI-VE", color: "Verde", colorHex: "#16a34a", stock: "bajo" },
    ],
    techniques: ["grabado-laser", "serigrafia"],
    isFeatured: true,
  },
  {
    id: "prod-10",
    name: "Taza Ceramica Sublimable 11oz",
    slug: "taza-ceramica-sublimable-11oz",
    description: "Taza de ceramica blanca con recubrimiento especial para sublimacion. 11oz de capacidad. Apta para lavavajillas y microondas.",
    shortDescription: "Taza ceramica 11oz para sublimacion.",
    categoryId: "cat-4",
    images: ["/images/products/taza-1.jpg"],
    price: 45,
    minOrder: 100,
    specs: [
      { label: "Capacidad", value: "11 oz (325 ml)" },
      { label: "Material", value: "Ceramica con recubrimiento" },
      { label: "Apta para", value: "Lavavajillas y microondas" },
      { label: "Area de impresion", value: "Envolvente 360°" },
    ],
    variants: [
      { sku: "TCS-BL", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "TCS-BI", color: "Blanco / Interior Color", colorHex: "#F5F5F5", stock: "disponible" },
    ],
    techniques: ["sublimacion"],
    isFeatured: false,
  },
  {
    id: "prod-11",
    name: "Botella Tritan 750ml",
    slug: "botella-tritan-750ml",
    description: "Botella deportiva de material Tritan libre de BPA. Tapa con asa integrada y boquilla anti-derrames. Ligera y resistente a impactos.",
    shortDescription: "Botella deportiva Tritan BPA-free 750ml.",
    categoryId: "cat-4",
    images: ["/images/products/botella-1.jpg"],
    price: 75,
    minOrder: 100,
    specs: [
      { label: "Capacidad", value: "750 ml" },
      { label: "Material", value: "Tritan (BPA free)" },
      { label: "Tapa", value: "Con asa y boquilla" },
      { label: "Area de impresion", value: "7 x 5 cm" },
    ],
    variants: [
      { sku: "BT7-TR", color: "Transparente", colorHex: "#e5e7eb", stock: "disponible" },
      { sku: "BT7-AZ", color: "Azul", colorHex: "#3b82f6", stock: "disponible" },
      { sku: "BT7-VE", color: "Verde", colorHex: "#22c55e", stock: "disponible" },
      { sku: "BT7-RO", color: "Rosa", colorHex: "#ec4899", stock: "bajo" },
    ],
    techniques: ["serigrafia", "tampografia"],
    isFeatured: false,
  },
  // Bolsas
  {
    id: "prod-12",
    name: "Bolsa Non-Woven Ecologica",
    slug: "bolsa-non-woven-ecologica",
    description: "Bolsa reutilizable de non-woven en multiples colores. Resistente y ecologica. Gran area de impresion. Ideal para ferias y eventos.",
    shortDescription: "Bolsa reutilizable non-woven ecologica.",
    categoryId: "cat-5",
    images: ["/images/products/bolsa-nw-1.jpg"],
    price: 18,
    minOrder: 200,
    specs: [
      { label: "Material", value: "Non-woven 80g" },
      { label: "Medidas", value: "35 x 40 x 10 cm" },
      { label: "Asas", value: "Reforzadas" },
      { label: "Area de impresion", value: "25 x 30 cm" },
    ],
    variants: [
      { sku: "BNW-BL", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "BNW-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "BNW-RO", color: "Rojo", colorHex: "#dc2626", stock: "disponible" },
      { sku: "BNW-AZ", color: "Azul Rey", colorHex: "#1d4ed8", stock: "disponible" },
      { sku: "BNW-VE", color: "Verde", colorHex: "#16a34a", stock: "disponible" },
      { sku: "BNW-AM", color: "Amarillo", colorHex: "#eab308", stock: "disponible" },
    ],
    techniques: ["serigrafia"],
    isFeatured: true,
  },
  {
    id: "prod-13",
    name: "Mochila Ejecutiva Laptop",
    slug: "mochila-ejecutiva-laptop",
    description: "Mochila ejecutiva con compartimento acolchado para laptop hasta 15.6 pulgadas. Multiples bolsillos organizadores. Espalda ergonomica con padding.",
    shortDescription: "Mochila ejecutiva para laptop 15.6\".",
    categoryId: "cat-5",
    brandId: "brand-5",
    images: ["/images/products/mochila-1.jpg"],
    price: 280,
    minOrder: 25,
    specs: [
      { label: "Material", value: "Poliester 600D" },
      { label: "Laptop", value: "Hasta 15.6 pulgadas" },
      { label: "Compartimentos", value: "3 principales + 5 bolsillos" },
      { label: "Area de bordado", value: "8 x 6 cm" },
    ],
    variants: [
      { sku: "MEL-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "MEL-GR", color: "Gris", colorHex: "#6b7280", stock: "disponible" },
    ],
    techniques: ["bordado", "serigrafia"],
    isFeatured: false,
  },
  // Oficina
  {
    id: "prod-14",
    name: "Libreta Pasta Dura A5",
    slug: "libreta-pasta-dura-a5",
    description: "Libreta profesional con pasta dura y 80 hojas rayadas de papel bond. Cierre elastico y separador de paginas. Bolsillo interior trasero.",
    shortDescription: "Libreta pasta dura A5 con 80 hojas.",
    categoryId: "cat-6",
    images: ["/images/products/libreta-1.jpg"],
    price: 55,
    minOrder: 100,
    specs: [
      { label: "Tamano", value: "A5 (14.5 x 21 cm)" },
      { label: "Hojas", value: "80 hojas rayadas" },
      { label: "Papel", value: "Bond 70g" },
      { label: "Area de impresion", value: "12 x 18 cm (portada)" },
    ],
    variants: [
      { sku: "LPD-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "LPD-AZ", color: "Azul", colorHex: "#2563eb", stock: "disponible" },
      { sku: "LPD-RO", color: "Rojo", colorHex: "#dc2626", stock: "disponible" },
      { sku: "LPD-VE", color: "Verde", colorHex: "#16a34a", stock: "bajo" },
    ],
    techniques: ["serigrafia", "grabado-laser"],
    isFeatured: true,
  },
  {
    id: "prod-15",
    name: "Organizador de Escritorio Bambu",
    slug: "organizador-escritorio-bambu",
    description: "Organizador de escritorio fabricado en bambu natural con compartimentos para plumas, tarjetas, celular y notas adhesivas. Ecologico y elegante.",
    shortDescription: "Organizador de escritorio en bambu.",
    categoryId: "cat-6",
    images: ["/images/products/organizador-1.jpg"],
    price: 120,
    minOrder: 50,
    specs: [
      { label: "Material", value: "Bambu natural" },
      { label: "Medidas", value: "22 x 10 x 11 cm" },
      { label: "Compartimentos", value: "5 secciones" },
      { label: "Area de grabado", value: "6 x 2 cm (frente)" },
    ],
    variants: [
      { sku: "OEB-NA", color: "Bambu Natural", colorHex: "#d4a76a", stock: "disponible" },
    ],
    techniques: ["grabado-laser"],
    isFeatured: false,
  },
  // More products
  {
    id: "prod-16",
    name: "Polo Pique Algodon",
    slug: "polo-pique-algodon",
    description: "Playera tipo polo en tejido pique de algodon con cuello y punos en rib. Corte clasico y moderno. Ideal para uniformes corporativos.",
    shortDescription: "Polo pique algodon para uniformes.",
    categoryId: "cat-1",
    images: ["/images/products/polo-1.jpg"],
    price: 135,
    minOrder: 50,
    specs: [
      { label: "Material", value: "Pique 100% Algodon" },
      { label: "Peso", value: "220 g/m2" },
      { label: "Tallas", value: "S, M, L, XL, 2XL" },
      { label: "Area de bordado", value: "10 x 8 cm (pecho)" },
    ],
    variants: [
      { sku: "PPA-BL", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "PPA-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "PPA-AM", color: "Azul Marino", colorHex: "#1e3a5f", stock: "disponible" },
      { sku: "PPA-GR", color: "Gris Jaspe", colorHex: "#9ca3af", stock: "disponible" },
    ],
    techniques: ["bordado", "serigrafia"],
    isFeatured: true,
  },
  {
    id: "prod-17",
    name: "Cargador Inalambrico Personalizado",
    slug: "cargador-inalambrico-personalizado",
    description: "Cargador inalambrico Qi compatible con todos los dispositivos. Superficie amplia con gran area para impresion. LED indicador de carga.",
    shortDescription: "Cargador inalambrico Qi con impresion.",
    categoryId: "cat-3",
    images: ["/images/products/cargador-1.jpg"],
    price: 165,
    minOrder: 50,
    specs: [
      { label: "Potencia", value: "10W / 7.5W / 5W" },
      { label: "Compatibilidad", value: "Qi universal" },
      { label: "Entrada", value: "Type-C" },
      { label: "Area de impresion", value: "Diametro 7 cm" },
    ],
    variants: [
      { sku: "CIP-BL", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "CIP-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "CIP-BB", color: "Bambu", colorHex: "#d4a76a", stock: "bajo" },
    ],
    techniques: ["serigrafia", "grabado-laser"],
    isFeatured: false,
  },
  {
    id: "prod-18",
    name: "Vaso Termico 20oz con Tapa",
    slug: "vaso-termico-20oz-con-tapa",
    description: "Vaso termico tipo tumbler de 20oz con doble pared de acero inoxidable y tapa deslizante. Mantiene temperatura por horas. Acabado mate exterior.",
    shortDescription: "Vaso termico tumbler 20oz acero inox.",
    categoryId: "cat-4",
    images: ["/images/products/vaso-1.jpg"],
    price: 110,
    minOrder: 50,
    specs: [
      { label: "Capacidad", value: "20 oz (590 ml)" },
      { label: "Material", value: "Acero inoxidable" },
      { label: "Tapa", value: "Deslizante anti-derrames" },
      { label: "Area de grabado", value: "7 x 5 cm" },
    ],
    variants: [
      { sku: "VT20-NE", color: "Negro Mate", colorHex: "#1a1a1a", stock: "disponible" },
      { sku: "VT20-BL", color: "Blanco", colorHex: "#FFFFFF", stock: "disponible" },
      { sku: "VT20-AZ", color: "Azul Marino", colorHex: "#1e3a5f", stock: "disponible" },
      { sku: "VT20-RG", color: "Rose Gold", colorHex: "#b76e79", stock: "disponible" },
    ],
    techniques: ["grabado-laser", "serigrafia"],
    isFeatured: false,
  },
  {
    id: "prod-19",
    name: "Bolsa de Lona Ecologica",
    slug: "bolsa-lona-ecologica",
    description: "Bolsa tote de lona de algodon natural de 12oz. Asas largas reforzadas. Alta calidad y gran durabilidad. 100% ecologica y reutilizable.",
    shortDescription: "Bolsa tote de lona algodon natural.",
    categoryId: "cat-5",
    images: ["/images/products/bolsa-lona-1.jpg"],
    price: 45,
    minOrder: 100,
    specs: [
      { label: "Material", value: "Lona de algodon 12oz" },
      { label: "Medidas", value: "38 x 42 cm" },
      { label: "Asas", value: "65 cm" },
      { label: "Area de impresion", value: "28 x 30 cm" },
    ],
    variants: [
      { sku: "BLE-NA", color: "Natural", colorHex: "#f5f0e1", stock: "disponible" },
      { sku: "BLE-NE", color: "Negro", colorHex: "#1a1a1a", stock: "disponible" },
    ],
    techniques: ["serigrafia", "sublimacion"],
    isFeatured: false,
  },
  {
    id: "prod-20",
    name: "Pluma Ecologica de Carton",
    slug: "pluma-ecologica-carton",
    description: "Boligrafo ecologico con cuerpo de carton reciclado y clip de madera. Tinta azul. Opcion sustentable y economica para grandes volumenes.",
    shortDescription: "Boligrafo ecologico de carton reciclado.",
    categoryId: "cat-2",
    images: ["/images/products/pluma-eco-1.jpg"],
    price: 8,
    minOrder: 500,
    specs: [
      { label: "Material", value: "Carton reciclado" },
      { label: "Largo", value: "14 cm" },
      { label: "Tinta", value: "Azul" },
      { label: "Area de impresion", value: "5 x 0.8 cm" },
    ],
    variants: [
      { sku: "PEC-CR", color: "Carton Natural", colorHex: "#c4a882", stock: "disponible" },
    ],
    techniques: ["tampografia"],
    isFeatured: false,
  },
];

export const brands: Brand[] = [
  {
    id: "brand-1",
    name: "Nike",
    slug: "nike",
    logo: "/images/brands/nike.svg",
    description: "Ropa deportiva premium para personalizar con tu marca.",
    website: "https://nike.com",
  },
  {
    id: "brand-2",
    name: "Cross",
    slug: "cross",
    logo: "/images/brands/cross.svg",
    description: "Instrumentos de escritura de lujo desde 1846.",
    website: "https://cross.com",
  },
  {
    id: "brand-3",
    name: "Parker",
    slug: "parker",
    logo: "/images/brands/parker.svg",
    description: "Plumas y boligrafos iconicos de alta gama.",
    website: "https://parker.com",
  },
  {
    id: "brand-4",
    name: "Anker",
    slug: "anker",
    logo: "/images/brands/anker.svg",
    description: "Tecnologia de carga lider en el mercado.",
    website: "https://anker.com",
  },
  {
    id: "brand-5",
    name: "Samsonite",
    slug: "samsonite",
    logo: "/images/brands/samsonite.svg",
    description: "Mochilas y maletines de calidad mundial.",
    website: "https://samsonite.com",
  },
  {
    id: "brand-6",
    name: "Termos Mexico",
    slug: "termos-mexico",
    logo: "/images/brands/termos-mexico.svg",
    description: "Termos y contenedores de acero inoxidable premium.",
  },
  {
    id: "brand-7",
    name: "Victorinox",
    slug: "victorinox",
    logo: "/images/brands/victorinox.svg",
    description: "Navajas suizas y accesorios de precision.",
    website: "https://victorinox.com",
  },
  {
    id: "brand-8",
    name: "Moleskine",
    slug: "moleskine",
    logo: "/images/brands/moleskine.svg",
    description: "Libretas y accesorios creativos iconicos.",
    website: "https://moleskine.com",
  },
];
